[build]
  publish = "exampleSite/public"
  command = "hugo --gc --minify --source exampleSite --themesDir ../.. --theme repo --baseURL https://www.icbmis.org/"

[context.production.environment]
HUGO_VERSION = "0.74.2"
HUGO_ENV = "production"
